# Generated by Django 4.1.7 on 2023-04-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_time_created_review_review_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_created',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_created',
            new_name='time_created',
        ),
    ]
