# Generated by Django 4.1.7 on 2023-05-04 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_rename_review_created_review_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0),
                                                               django.core.validators.MaxValueValidator(5)]),
        ),
    ]
