# Generated by Django 4.1.7 on 2023-05-04 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_body_alter_review_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0),
                                                                          django.core.validators.MaxValueValidator(5)],
                                                   verbose_name='Note'),
        ),
    ]
